sample-data/important.json, sample-data/urgent.json
=> Add sample tags data.

src/main/java/org/folio/rest/impl/TagsResourceImpl.java, src/test/java/org/folio/rest/impl/TagsTest.java
Change format of error message
=> MODTAG-18 reword duplicate label message

pom.xml, src/main/java/org/folio/rest/impl/TagsResourceImpl.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/TagsTest.java
Most of the PgUtil.* methods do not support JSON error messages with status 422.
=> MODTAG-17: Upgrade to RMB 26

pom.xml
=> MODTAG-34  Upgrade to RMB v.29.x

pom.xml, ramls/tag.json, ramls/tags.raml, src/main/java/org/folio/rest/impl/TagsResourceImpl.java, src/main/java/org/folio/rest/impl/TenantRefAPI.java, src/test/java/org/folio/rest/impl/TagsTest.java
Upgrade RMB version to v30.0.0
=> MODTAG-38 Update to RMB v30.0.0

pom.xml
=> MODTAG-39  mod-tags: Update to RMB v31.x

README.md
Also testing new jenkins-slave-all:java-11 build image
=> FOLIO-2855 generate-api-docs 

Jenkinsfile
See [FOLIO-2893](https://issues.folio.org/browse/FOLIO-2893)
Replace "runLintRamlCop" with "doApiLint".
=> FOLIO-2893 Use api-lint

NEWS.md, pom.xml
=> MODTAG-57 Upgrade spring-base to 2.0.0

src/main/resources/db/changelog/changes/v1.0.0/create-tags-table.xml
fix the error during the module update - https://issues.folio.org/browse/MODTAG-58
=> MODTAG-58 - Fix liquibase error

pom.xml
Log4j vulnerability verification and correction
=> MODTAG-62 Log4j vulnerability verification and correction

descriptors/DeploymentDescriptor-template.json
https://issues.folio.org/browse/MODTAG-71
=> Fix deployment has incorrect jar and port MODTAG-71

CODEOWNERS, PULL_REQUEST_TEMPLATE.md, doc/RELEASES.md, pom.xml
1. Make it possible to run mvn compile twice
2. Add CODEOWNERS, PULL_REQUEST_TEMPLATE and RELEASES
To make it possible to compile twice clean-plugin was added to pom.xml
=> MODTAG-70 Improve pom.xml and add docs

src/main/resources/db/changelog/changes/v1.0.0/_cleanup-rmb.xml
Update RMB-cleanup scripts with specifying the schema. Use ${database.defaultSchemaName} where you need schema name
Use ${database.defaultSchemaName}
https://issues.folio.org/browse/MODTAG-81
=> MODTAG-81 Update RMB-cleanup scripts with specifying the schema

checkstyle/checkstyle.xml, pom.xml, src/main/java/org/folio/tags/controller/ErrorHandlingAdvice.java, src/main/java/org/folio/tags/controller/TagsController.java, src/main/java/org/folio/tags/dao/FolioAuditorAware.java, src/main/java/org/folio/tags/dao/model/Tag.java, src/main/java/org/folio/tags/dao/repository/TagRepository.java, src/main/java/org/folio/tags/mapper/TagsMapper.java, src/main/java/org/folio/tags/service/TagService.java, src/main/java/org/folio/tags/service/TagServiceImpl.java, src/main/java/org/folio/tags/util/ErrorsHelper.java, src/test/java/org/folio/tags/controller/TagsApiTest.java, src/test/java/org/folio/tags/support/ApiTest.java, src/test/java/org/folio/tags/support/DatabaseHelper.java
- Add checkstyle maven plugin
- Fix checkstyle violations
https://issues.folio.org/browse/MODTAG-94
=> MODTAG-94 Add checkstyle maven plugin

NEWS.md, doc/RELEASES.md, pom.xml
Release v1.3.0
[MODTAG-96](https://issues.folio.org/browse/MODTAG-96)
=> Tmp release v1.3.0

PULL_REQUEST_TEMPLATE.md, src/main/resources/application.yaml
_Logging should be improved for more productive troubleshooting._
- Check that log4j2.properties doesn't exist or it is aligned with https://wiki.folio.org/display/DD/Folio+logging+solution
- Enable the /loggers endpoint in our application.properties file by adding the following lines:
- management.endpoints.web.exposure.include=loggers
- management.endpoint.loggers.enabled=true
- The version of the folio-spring-base should be updated (see [FOLSPRINGB-45](https://issues.folio.org/browse/FOLSPRINGB-45))
- Add step "Check logging" to PULL_REQUEST_TEMPLATE.md
https://issues.folio.org/browse/MODTAG-100
=> MODTAG-100 - Logging improvement - Configuration

Dockerfile, Jenkinsfile, pom.xml, src/main/java/org/folio/tags/ModTagsApplication.java, src/main/java/org/folio/tags/controller/ErrorHandlingAdvice.java, src/main/java/org/folio/tags/dao/model/Tag.java, src/main/java/org/folio/tags/service/TagServiceImpl.java, src/main/resources/application.yaml, src/test/java/org/folio/tags/controller/TagsApiTest.java, src/test/java/org/folio/tags/support/ApiTest.java, src/test/resources/application-test.yaml
https://issues.folio.org/browse/MODTAG-101 : mod-tags: Update to Java 17
https://issues.folio.org/browse/MODTAG-102: mod-tags: Update the module to Spring boot v3.0.0 and identify issues.
Migrating to Spring Boot v3.0.0: https://wiki.folio.org/display/~Taras_Spashchenko/Migration+to+Spring+Boot+v3.0.0+How+to?src=contextnavpagetreemode
=> MODTAG-101: Update to Java 17 (Update the module to Spring boot v3.0.1)

pom.xml, src/main/resources/application.yaml
Update deprecated property and upgrade folio-spring-base version
Migrating to Spring Boot v3.0.0: https://wiki.folio.org/display/~Taras_Spashchenko/Migration+to+Spring+Boot+v3.0.0+How+to?src=contextnavpagetreemode
[https://issues.folio.org/browse/MODTAG-101](https://issues.folio.org/browse/MODTAG-101)
=> MODTAG-101: minor fixes for spring boot upgrade

src/main/java/org/folio/tags/service/TagServiceImpl.java
Improve logging
Added appropriate logs to necessary places.
[https://issues.folio.org/browse/MODTAG-73](https://issues.folio.org/browse/MODTAG-73)
=> MODTAG-73: Improved logging where possible

NEWS.md
- Update NEWS.md
- Release v2.0.1
=> MODTAG-109 Update NEWS v2.0.1

pom.xml
Upgrade Folio spring base dependency version
=> MODTAG-119 Upgrade Folio spring base dependency version

pom.xml
Upgrade spring boot starter dependency version to 3.1.4
=> MODTAG-120 Upgrade spring boot starter dependency version

NEWS.md, pom.xml
=> MODTAG-118 Poppy Release

NEWS.md, pom.xml
=> MODTAG-122 - Release 2.2.0 for Q

.github/workflows/postgres.yml, pom.xml, src/test/java/org/folio/tags/support/ApiTest.java
=> MODTAG-126 - Upgrade folio spring support version.

pom.xml
=> MODTAG-127 - Upgrade versions for Ramsons release.

NEWS.md, pom.xml
=> Ramsons Release

.github/workflows/postgres.yml, Dockerfile, Jenkinsfile, pom.xml
=> FOLIO-4221 - Java, spring upgrades

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/MODTAG-131
=> Sunflower release 2.4.0
